// Copy this file, rename to 'config.js', and paste in the values
module.exports = {
  G_ID: 'CLIENT_ID_GOES_HERE',
  G_SECRET: 'CLIENT_SECRET_GOES_HERE',
  SESSION_SECRET: 'SESSION_SECRET_GOES_HERE',
  GOOGLE_KEY: 'GOOGLE_API_KEY_GOES_HERE',
  DARK_SKY_KEY: 'DARK_SKY_KEY_GOES_HERE',
  FLIGHT_API_KEY: 'FLIGHT_API_KEY_GOES_HERE',
  FLIGHT_APP_KEY: 'FLIGHT_APP_KEY_GOES_HERE'
};
